name: Mac Build

on:
  push:
    branches: 
        - main
        - feature/* 
        - bugfix/*
        - develop
        - bugfix/*
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: init
      run: mkdir build    
    - name: update submodules
      run: git submodule update --init --recursive --remote
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: build
    - name: build
      run: cmake --build .
      working-directory: build
    # - name: pack
    #   run: cmake --build . --config Release --target package
    #   working-directory: build
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: werckmeister-mac-${{ github.sha }}
    #     path: |
    #       build/werckmeister-*-Darwin.sh
    #       rendertests/*.mid
